### ISSUE TITLE
[Feature] 명준식 v2

### ISSUE THREAD

**Issue by grayashh** [ConvergenceSwAce/22-F-SchoolMeal#126]
**Description**
처음부터 새로 작성하여 무결한 서비스를 제작하려 함
---

**TODO**
- [X] JS-> TS로 변경 #125 
- [X] native-base 세팅 #130 
- [X] Tailwind 세팅 #125 
- [x] Recoil -> Redux로 변경
- [x] Redux-Query 세팅
- [x] #127
- [x] #128
~[ ] #129~ -> 2.1 업데이트 사항

---

**ETC**
기타사항
