### ISSUE TITLE
기능 구현

### ISSUE THREAD

**Issue by grayashh** [ConvergenceSwAce/22-F-SchoolMeal#128]
**Description**
API 연동, 상태 관리, 캠퍼스 설정 등 기능 구현
---

**TODO**
- [x] React-Query API 연동 및 캐싱 #132 
- [x] Redux 상태 관리 #132 
- [x] Async storage 캠퍼스 설정 #135 

---

**ETC**
기타사항
