### ISSUE TITLE
추가 기능 구현

### ISSUE THREAD

**Issue by grayashh** [ConvergenceSwAce/22-F-SchoolMeal#129]
**Description**
메뉴 룰렛, 주변 맛집 지도 등 추가 기능 기획 필요
---

**TODO**
- [ ] 메뉴 룰렛 
- [ ] 주변 식당 지도 (카카오맵 API 연동)
- [ ] 앱 사용시 리뷰 요청 push
- [ ] 설정에서 리뷰 리다이렉트 및 후원 메뉴

---

**ETC**
기타사항
