### ISSUE TITLE
[Feature] 버튼 기능구현

### ISSUE THREAD

**Issue by MinsuKim21** [ConvergenceSwAce/22-F-SchoolMeal#26]
**Description**
버튼 클릭시 색상 변경 및 모달창으로 체크리스트 띄우기
체크리스트는 다중선택으로 해야하고, 리스트가 중식과 석식이 따로 있어야함
---

**TODO**
- [x] 터치시 모달 띄움과 색상 변경
- [x] 체크리스트 다중선택
- [x] 중식, 석식 나눠서 나와야함
- [x] 체크된 리스트를 묶어서 good 또는 bad 버튼 터치시 post
- [x] bad 버튼 터치시 컴포넌트 삭제
- [x] 사용자가 이미 체크한적이 있다면, 데이터 Update 해야함

---

**ETC**
기타사항
