### ISSUE TITLE
[Feature] week carousel의 날짜 또는 요일을 터치시 메뉴 불러오기

### ISSUE THREAD

**Issue by MinsuKim21** [ConvergenceSwAce/22-F-SchoolMeal#28]
**Description**
week 요일 또는 날짜 터치시 해당 요일 또는 날짜에 맞는 데이터를 불러와야함
크롤러가 전 주, 다음 주, 요번 주 세가지 있어서 3주간 데이터를 부를수있긴한디... 전 주, 다음 주 데이터를 꼭 불러야 할까? 근디 중고딩때 미래 급식이나 이전 급식 자주 찾아보긴 했었는디.. 암튼 학식도 안정기 되면 한달 단위로 업데이트 될수도? 그런거 감안하면 전 주, 다음 주 데이터 도 불러올 수 있게하는게 맞는듯 코맨트 달아주셈 
---

**TODO**
- [x] 요일 터치시 해당 요일에 맞는 데이터 불러오기
- [x] 요일 터치시 해당 요일에 포커스
- [x] 오늘 날짜에 focus해주어야 함
- [ ] #61

---

**ETC**
기타사항

**Comment by grayashh** [comment]
일단은 터치 다 비활성화 시키고 carousel말고 그냥 날짜에 맞게 background 그려주는 식으로 가야될 듯 
사람들 저번주 다음주 불러오게 되면 트래픽 문제도 있고 지금 저번주, 다음주 불러오는게 함수로 불러오는게 아니라 헤더로 불러오는거라 셀레늄으로 @wnd180 가 금요일에 만들면 다시 논의

**Comment by MinsuKim21** [comment]
ㅇㅋㅇㅋ
