### ISSUE TITLE
[Build] 빌드 테스트 및 앱 이름 변경

### ISSUE THREAD

**Issue by MinsuKim21** [ConvergenceSwAce/22-F-SchoolMeal#50]
**Description**
ㅈㄱㄴ

---

**TODO**
- [x] ios
- [x] ios 앱이름 변경
- [x] 안드로이드
- [X] 안드로이드 앱 이름 변경 (겔럭시 22 스넵드레곤은 확인했음)
- [x] 안드로이드 다중 APK 적용

---

**ETC**
기타사항
