### ISSUE TITLE
[Feature] Bug Fix Update 

### ISSUE THREAD

**Issue by grayashh** [ConvergenceSwAce/22-F-SchoolMeal#75]
**Description**
1.5 버전 업데이트 예정 내역
---

**TODO**
- [x] Add Yong-in Campus Meal info (자연캠퍼스 추가)
- [x] IOS Launch Screen Fix (IOS Launch Screen 수정)
- [x] Button Touch Layout & Responsive Fix (버튼 터치 영역, 설문 폼 디자인 수정) #74 
- [x] ~~Prevent Double Submit (중복 제출 방지) #58 & #60~~
- [x] ~~Add Insights based on voting results (투표 결과에 따른 인사이트 추가)~~
- [x] #76

---

**ETC**
기타사항

**Comment by wnd180** [comment]
주말 ![image](https://user-images.githubusercontent.com/23502888/197378549-8253f309-0b7c-4227-ae46-feb1b1297fab.png)28일로 잡힘

**Comment by wnd180** [comment]
Widget, notification 논의 필요
